import { createMockAdapter } from '../core/adapters/createMockAdapter'
import { mergeSymbolSpec, type SymbolSpec } from '../core/symbols/SymbolSpec'

const symbols: SymbolSpec[] = [
  mergeSymbolSpec({
    symbol: 'BTCUSDT',
    displayName: 'BTC/USDT',
    marketId: 'crypto',
    assetClass: 'crypto-perp',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.1,
    lotSize: 0.001,
    contractSize: 1,
    tickValue: 0.1,
    priceDecimals: 2,
    qtyDecimals: 4,
    defaultLeverage: 10,
    minQty: 0.001,
    maxQty: 500,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 97_250,
    tvSymbol: 'BINANCE:BTCUSDT',
  }),
  mergeSymbolSpec({
    symbol: 'ETHUSDT',
    displayName: 'ETH/USDT',
    marketId: 'crypto',
    assetClass: 'crypto-perp',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.05,
    lotSize: 0.001,
    contractSize: 1,
    tickValue: 0.05,
    priceDecimals: 2,
    qtyDecimals: 4,
    defaultLeverage: 10,
    minQty: 0.001,
    maxQty: 10_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 3_542,
    tvSymbol: 'BINANCE:ETHUSDT',
  }),
  mergeSymbolSpec({
    symbol: 'SOLUSDT',
    displayName: 'SOL/USDT',
    marketId: 'crypto',
    assetClass: 'crypto-perp',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.01,
    lotSize: 0.01,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 2,
    defaultLeverage: 15,
    minQty: 0.01,
    maxQty: 500_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 178.5,
    tvSymbol: 'BINANCE:SOLUSDT',
  }),
  mergeSymbolSpec({
    symbol: 'XRPUSDT',
    displayName: 'XRP/USDT',
    marketId: 'crypto',
    assetClass: 'crypto-perp',
    quoteCurrency: 'USDT',
    marginCurrency: 'USDT',
    tickSize: 0.0001,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.0001,
    priceDecimals: 4,
    qtyDecimals: 2,
    defaultLeverage: 10,
    minQty: 1,
    maxQty: 10_000_000,
    sessionType: '24h',
    pnlFormulaType: 'linear',
    referencePrice: 2.31,
    tvSymbol: 'BINANCE:XRPUSDT',
  }),
]

export const cryptoMockAdapter = createMockAdapter({
  id: 'crypto-mock',
  marketId: 'crypto',
  displayName: '코인 (Mock)',
  symbols,
  tickIntervalMs: 500,
  tick: { sigmaRatio: 0.0015, depth: 14 },
})
