import { createMockAdapter } from '../core/adapters/createMockAdapter'
import { mergeSymbolSpec, type SymbolSpec } from '../core/symbols/SymbolSpec'

const symbols: SymbolSpec[] = [
  mergeSymbolSpec({
    symbol: 'NQ',
    displayName: 'NASDAQ 100 Fut',
    marketId: 'global-futures',
    assetClass: 'futures',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.25,
    lotSize: 1,
    contractSize: 1,
    tickValue: 5,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 20,
    minQty: 1,
    maxQty: 5_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 19_820,
    tvSymbol: 'CME_MINI:NQ1!',
  }),
  mergeSymbolSpec({
    symbol: 'ES',
    displayName: 'S&P 500 Fut',
    marketId: 'global-futures',
    assetClass: 'futures',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.25,
    lotSize: 1,
    contractSize: 1,
    tickValue: 12.5,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 20,
    minQty: 1,
    maxQty: 5_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 5_812,
    tvSymbol: 'CME_MINI:ES1!',
  }),
  mergeSymbolSpec({
    symbol: 'GC',
    displayName: 'Gold Fut',
    marketId: 'global-futures',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.1,
    lotSize: 1,
    contractSize: 1,
    tickValue: 10,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 20,
    minQty: 1,
    maxQty: 2_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 2_345.6,
    tvSymbol: 'COMEX:GC1!',
  }),
  mergeSymbolSpec({
    symbol: 'CL',
    displayName: 'Crude Oil Fut',
    marketId: 'global-futures',
    assetClass: 'commodity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.01,
    lotSize: 1,
    contractSize: 1,
    tickValue: 10,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 20,
    minQty: 1,
    maxQty: 2_000,
    sessionType: 'futures_session',
    pnlFormulaType: 'futures_contract',
    referencePrice: 71.4,
    tvSymbol: 'NYMEX:CL1!',
  }),
]

export const globalFuturesMockAdapter = createMockAdapter({
  id: 'global-futures-mock',
  marketId: 'global-futures',
  displayName: '해외선물 (Mock)',
  symbols,
  tickIntervalMs: 600,
  tick: { sigmaRatio: 0.0012, depth: 14 },
})
