import { createMockAdapter } from '../core/adapters/createMockAdapter'
import { mergeSymbolSpec, type SymbolSpec } from '../core/symbols/SymbolSpec'

const symbols: SymbolSpec[] = [
  mergeSymbolSpec({
    symbol: '005930',
    displayName: '삼성전자',
    marketId: 'kr-stock',
    assetClass: 'equity',
    quoteCurrency: 'KRW',
    marginCurrency: 'KRW',
    tickSize: 50,
    lotSize: 1,
    contractSize: 1,
    tickValue: 50,
    priceDecimals: 0,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 78_400,
    tvSymbol: 'KRX:005930',
  }),
  mergeSymbolSpec({
    symbol: '000660',
    displayName: 'SK하이닉스',
    marketId: 'kr-stock',
    assetClass: 'equity',
    quoteCurrency: 'KRW',
    marginCurrency: 'KRW',
    tickSize: 100,
    lotSize: 1,
    contractSize: 1,
    tickValue: 100,
    priceDecimals: 0,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 184_500,
    tvSymbol: 'KRX:000660',
  }),
  mergeSymbolSpec({
    symbol: '035720',
    displayName: '카카오',
    marketId: 'kr-stock',
    assetClass: 'equity',
    quoteCurrency: 'KRW',
    marginCurrency: 'KRW',
    tickSize: 50,
    lotSize: 1,
    contractSize: 1,
    tickValue: 50,
    priceDecimals: 0,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 42_350,
    tvSymbol: 'KRX:035720',
  }),
]

export const krStockMockAdapter = createMockAdapter({
  id: 'kr-stock-mock',
  marketId: 'kr-stock',
  displayName: '국내주식 (Mock)',
  symbols,
  tickIntervalMs: 1_000,
  tick: { sigmaRatio: 0.0008, depth: 10 },
})
