import { createMockAdapter } from '../core/adapters/createMockAdapter'
import { mergeSymbolSpec, type SymbolSpec } from '../core/symbols/SymbolSpec'

const symbols: SymbolSpec[] = [
  mergeSymbolSpec({
    symbol: 'AAPL',
    displayName: 'Apple Inc.',
    marketId: 'us-stock',
    assetClass: 'equity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.01,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 212.5,
    tvSymbol: 'NASDAQ:AAPL',
  }),
  mergeSymbolSpec({
    symbol: 'TSLA',
    displayName: 'Tesla, Inc.',
    marketId: 'us-stock',
    assetClass: 'equity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.01,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 248.9,
    tvSymbol: 'NASDAQ:TSLA',
  }),
  mergeSymbolSpec({
    symbol: 'NVDA',
    displayName: 'NVIDIA Corp.',
    marketId: 'us-stock',
    assetClass: 'equity',
    quoteCurrency: 'USD',
    marginCurrency: 'USD',
    tickSize: 0.01,
    lotSize: 1,
    contractSize: 1,
    tickValue: 0.01,
    priceDecimals: 2,
    qtyDecimals: 0,
    defaultLeverage: 1,
    minQty: 1,
    maxQty: 1_000_000,
    sessionType: 'regular',
    pnlFormulaType: 'stock',
    referencePrice: 138.4,
    tvSymbol: 'NASDAQ:NVDA',
  }),
]

export const usStockMockAdapter = createMockAdapter({
  id: 'us-stock-mock',
  marketId: 'us-stock',
  displayName: '미국주식 (Mock)',
  symbols,
  tickIntervalMs: 900,
  tick: { sigmaRatio: 0.0009, depth: 10 },
})
