import type { TradingWindowPreset, TradingWindowProfileId } from './tradingWindowPresetTypes'
import { TRADING_WINDOW_SCHEMA_VERSION } from './tradingWindowPresetTypes'

const MOBILE_STACK_DEFAULT = [
  'ticker',
  'chart',
  'book',
  'order',
  'history',
] as const

function baseMobile(
  overrides: Partial<TradingWindowPreset['mobile']> = {},
): TradingWindowPreset['mobile'] {
  return {
    stackOrder: [...MOBILE_STACK_DEFAULT],
    stickyHeader: 'ticker',
    bottomSheetOrder: 'half',
    thumbZone: 'balanced',
    compactTicker: true,
    ...overrides,
  }
}

export const MOCK_TRADING_WINDOW_PROFILES: Record<TradingWindowProfileId, TradingWindowPreset> = {
  'private-bank': {
    schemaVersion: TRADING_WINDOW_SCHEMA_VERSION,
    mockOnly: true,
    profileId: 'private-bank',
    label: '프라이빗뱅크형',
    orderBook: {
      layout: 'two-column',
      levelCount: 10,
      spreadHighlight: 'subtle',
      clickToFill: 'on',
      density: 'airy',
    },
    chartLayout: {
      toolbar: 'minimal',
      timeframeStrip: 'hidden',
      domStrip: 'hidden',
      studies: 'off',
      aspectPolicy: 'fill',
    },
    positionPanel: {
      dockHeight: 'short',
      defaultTab: 'positions',
      columnSet: 'retail',
      pnlEmphasis: 'hero',
      showMarginBlock: false,
    },
    orderForm: {
      layout: 'vertical',
      primaryAction: 'buy-sell-tabs',
      advanced: 'collapsed',
      qtyInput: 'notional',
      confirmModal: 'mock-only',
    },
    speedOrder: {
      integrationState: 'planned',
      moduleLabels: {},
      hotkeysStrip: 'hidden',
      vendorSnapshot: 'off',
    },
    mobile: baseMobile({ bottomSheetOrder: 'full', compactTicker: true }),
  },
  'broker-hts': {
    schemaVersion: TRADING_WINDOW_SCHEMA_VERSION,
    mockOnly: true,
    profileId: 'broker-hts',
    label: '증권사 HTS',
    orderBook: {
      layout: 'center-ladder',
      levelCount: 15,
      spreadHighlight: 'bold',
      clickToFill: 'on',
      density: 'standard',
    },
    chartLayout: {
      toolbar: 'standard',
      timeframeStrip: 'top',
      domStrip: 'hidden',
      studies: 'badges-only',
      aspectPolicy: 'fill',
    },
    positionPanel: {
      dockHeight: 'standard',
      defaultTab: 'positions',
      columnSet: 'retail',
      pnlEmphasis: 'standard',
      showMarginBlock: false,
    },
    orderForm: {
      layout: 'vertical',
      primaryAction: 'buy-sell-tabs',
      advanced: 'accordion',
      qtyInput: 'shares',
      confirmModal: 'off',
    },
    speedOrder: {
      integrationState: 'in-progress',
      moduleLabels: {
        chart: 'ChartArea + DOM',
        orderBook: 'OrderBookPanel (HTS)',
        orderPanel: 'SpeedOrderPanel + StopMit',
        dock: 'PositionPanel + TradeHistoryPanel',
      },
      hotkeysStrip: 'mock',
      vendorSnapshot: 'strip',
    },
    mobile: baseMobile(),
  },
  'global-futures': {
    schemaVersion: TRADING_WINDOW_SCHEMA_VERSION,
    mockOnly: true,
    profileId: 'global-futures',
    label: '해외선물/바이낸스형',
    orderBook: {
      layout: 'compact-ladder',
      levelCount: 20,
      spreadHighlight: 'bold',
      clickToFill: 'on',
      density: 'compact',
    },
    chartLayout: {
      toolbar: 'pro',
      timeframeStrip: 'top',
      domStrip: 'bottom',
      studies: 'expanded',
      aspectPolicy: 'fill',
    },
    positionPanel: {
      dockHeight: 'standard',
      defaultTab: 'open-orders',
      columnSet: 'pro',
      pnlEmphasis: 'standard',
      showMarginBlock: true,
    },
    orderForm: {
      layout: 'ticket-compact',
      primaryAction: 'dual-buttons',
      advanced: 'always-visible',
      qtyInput: 'contracts',
      confirmModal: 'off',
    },
    speedOrder: {
      integrationState: 'in-progress',
      moduleLabels: {
        chart: 'Futures chart (mock)',
        orderBook: 'Depth ladder',
        orderPanel: 'Futures ticket',
        dock: 'Positions · margin',
      },
      hotkeysStrip: 'mock',
      vendorSnapshot: 'strip',
    },
    mobile: baseMobile({ thumbZone: 'right', compactTicker: false }),
  },
  'institutional-desk': {
    schemaVersion: TRADING_WINDOW_SCHEMA_VERSION,
    mockOnly: true,
    profileId: 'institutional-desk',
    label: '기관 데스크형',
    orderBook: {
      layout: 'depth-heatmap',
      levelCount: 20,
      spreadHighlight: 'none',
      clickToFill: 'off',
      density: 'compact',
    },
    chartLayout: {
      toolbar: 'pro',
      timeframeStrip: 'floating',
      domStrip: 'side',
      studies: 'expanded',
      aspectPolicy: 'fixed-16-9',
    },
    positionPanel: {
      dockHeight: 'tall',
      defaultTab: 'fills',
      columnSet: 'institutional',
      pnlEmphasis: 'muted',
      showMarginBlock: true,
    },
    orderForm: {
      layout: 'institutional-ticket',
      primaryAction: 'side-toggle',
      advanced: 'always-visible',
      qtyInput: 'contracts',
      confirmModal: 'mock-only',
    },
    speedOrder: {
      integrationState: 'planned',
      moduleLabels: {
        chart: 'Desk chart (mock)',
        orderBook: 'Institutional depth',
        orderPanel: 'Block ticket',
        dock: 'Blotter',
      },
      hotkeysStrip: 'hidden',
      vendorSnapshot: 'off',
    },
    mobile: baseMobile({ stickyHeader: 'none', bottomSheetOrder: 'off' }),
  },
  'mobile-mts': {
    schemaVersion: TRADING_WINDOW_SCHEMA_VERSION,
    mockOnly: true,
    profileId: 'mobile-mts',
    label: '모바일 MTS형',
    orderBook: {
      layout: 'compact-ladder',
      levelCount: 10,
      spreadHighlight: 'subtle',
      clickToFill: 'on',
      density: 'compact',
    },
    chartLayout: {
      toolbar: 'minimal',
      timeframeStrip: 'top',
      domStrip: 'hidden',
      studies: 'badges-only',
      aspectPolicy: 'fill',
    },
    positionPanel: {
      dockHeight: 'short',
      defaultTab: 'positions',
      columnSet: 'retail',
      pnlEmphasis: 'standard',
      showMarginBlock: false,
    },
    orderForm: {
      layout: 'ticket-compact',
      primaryAction: 'dual-buttons',
      advanced: 'collapsed',
      qtyInput: 'shares',
      confirmModal: 'off',
    },
    speedOrder: {
      integrationState: 'planned',
      moduleLabels: {},
      hotkeysStrip: 'hidden',
      vendorSnapshot: 'off',
    },
    mobile: baseMobile({
      stackOrder: ['ticker', 'chart', 'order', 'book', 'history'],
      stickyHeader: 'ticker',
      bottomSheetOrder: 'full',
      thumbZone: 'balanced',
      compactTicker: true,
    }),
  },
}
