import type { TenantWhitelabelPreset } from './tenantPresetTypes'
import { WHITELABEL_SCHEMA_VERSION } from './tenantPresetTypes'

const baseTypography = {
  fontSans: "'Pretendard Variable', Pretendard, system-ui, sans-serif",
  fontMono: "'JetBrains Mono', ui-monospace, monospace",
  baseSizePx: 14,
  headingWeight: 600,
} as const

export const MOCK_TENANT_PRESETS: TenantWhitelabelPreset[] = [
  {
    schemaVersion: WHITELABEL_SCHEMA_VERSION,
    id: 'goldx',
    brandName: 'GOLDX',
    tenantId: 'goldx-tenant',
    companyId: 'goldx-holdings',
    mockOnly: true,
    theme: {
      colors: {
        bg: '#0c0a08',
        surface: '#14110c',
        surface2: '#1c1810',
        border: '#2a2418',
        text: '#f5f0e6',
        muted: '#9a8f7a',
        bid: '#c9a227',
        ask: '#e85d4a',
        accent: '#d4a017',
        accent2: '#b8860b',
        warn: '#e6a817',
      },
      typography: { ...baseTypography, headingWeight: 700 },
      chartStyle: 'gradient',
      spacing: 'comfortable',
      borderRadius: 'rounded',
    },
    layout: {
      sidebarWidth: 'wide',
      topbarStyle: 'elevated',
      cardLayout: 'bordered',
      gridDensity: 'standard',
    },
    menu: 'broker-style',
    admin: 'banking',
  },
  {
    schemaVersion: WHITELABEL_SCHEMA_VERSION,
    id: 'bluetrade',
    brandName: 'BLUETRADE',
    tenantId: 'bluetrade-tenant',
    companyId: 'bluetrade-securities',
    mockOnly: true,
    theme: {
      colors: {
        bg: '#060a12',
        surface: '#0d1424',
        surface2: '#121c32',
        border: '#1a2844',
        text: '#e8eef8',
        muted: '#7b8aa8',
        bid: '#22c55e',
        ask: '#ef4444',
        accent: '#2563eb',
        accent2: '#3b82f6',
        warn: '#f59e0b',
      },
      typography: baseTypography,
      chartStyle: 'minimal',
      spacing: 'comfortable',
      borderRadius: 'rounded',
    },
    layout: {
      sidebarWidth: 'standard',
      topbarStyle: 'flat',
      cardLayout: 'elevated',
      gridDensity: 'standard',
    },
    menu: 'trading-first',
    admin: 'trading-desk',
  },
  {
    schemaVersion: WHITELABEL_SCHEMA_VERSION,
    id: 'prime-futures',
    brandName: 'PRIME FUTURES',
    tenantId: 'prime-futures-tenant',
    companyId: 'prime-futures-llc',
    mockOnly: true,
    theme: {
      colors: {
        bg: '#050608',
        surface: '#0a0e14',
        surface2: '#101620',
        border: '#1a2230',
        text: '#e4f4ff',
        muted: '#6b8a9e',
        bid: '#00e5a0',
        ask: '#ff4d6d',
        accent: '#00d4ff',
        accent2: '#a855f7',
        warn: '#fbbf24',
      },
      typography: { ...baseTypography, baseSizePx: 13 },
      chartStyle: 'neon',
      spacing: 'compact',
      borderRadius: 'sharp',
    },
    layout: {
      sidebarWidth: 'narrow',
      topbarStyle: 'glass',
      cardLayout: 'flat',
      gridDensity: 'dense',
    },
    menu: 'futures-style',
    admin: 'modern-glass',
  },
]
